export interface Project {
  slug: string
  title: string
  category: string
  img: string
  desc: string
  client: string
  location: string
  year: string
  duration: string
  problem: string
  solution: string
  results: { metric: string; value: string }[]
  testimonial?: { quote: string; author: string; role: string }
}

export const projects: Record<string, Project[]> = {
  id: [
    {
      slug: 'optimasi-hvac-pabrik-makanan',
      title: 'Optimasi HVAC - Pabrik Makanan',
      category: 'HVAC Optimization',
      img: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=1200',
      desc: 'Redesain sistem HVAC menyeluruh untuk fasilitas pemrosesan makanan besar.',
      client: 'Pabrik Makanan Ringan — Jawa Barat',
      location: 'Bandung, Jawa Barat',
      year: '2024',
      duration: '6 bulan',
      problem: 'Fasilitas pemrosesan makanan 15.000 m² menghadapi tagihan listrik pendinginan Rp 450 juta/bulan. Sistem HVAC lama (12 tahun) beroperasi di bawah kapasitas optimal, dengan COP rata-rata 2.8 — jauh di bawah standar industri 5.0+.',
      solution: 'Auditi seluruh sistem pendingin, lalu desain ulang menggunakan LiBr Absorption Chiller 500 RT yang memanfaatkan waste heat dari boiler produksi. Tambahkan Variable Speed Drive (VSD) pada 18 unit fan coil dan instalasi BMS (Building Management System) untuk monitoring real-time.',
      results: [
        { metric: 'Penghematan Energi', value: '35%' },
        { metric: 'ROI', value: '18 bulan' },
        { metric: 'COP Baru', value: '5.2' },
        { metric: 'Penurunan Tagihan Listrik', value: 'Rp 157 juta/bulan' },
      ],
      testimonial: {
        quote: 'BGE berhasil mengubah sistem pendingin kami dari beban terbesar menjadi aset efisiensi. Penghematan 35% melebihi ekspektasi kami.',
        author: 'Andi Kurniawan',
        role: 'Plant Manager',
      },
    },
    {
      slug: 'energy-management-gedung-perkantoran',
      title: 'Energy Management System - Gedung Perkantoran',
      category: 'Energy Management',
      img: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200',
      desc: 'Sistem manajemen energi terintegrasi untuk kantor pusat korporat 20 lantai.',
      client: 'Korporat Properti — Jakarta Selatan',
      location: 'Jakarta Selatan',
      year: '2024',
      duration: '8 bulan',
      problem: 'Gedung perkantoran 20 lantai dengan luas 45.000 m² mengonsumsi energi 2.800.000 kWh/tahun. Tidak ada sistem monitoring terpusat, sehingga pemborosan energi dari pencahayaan, pendingin, dan lift tidak terdeteksi.',
      solution: 'Implementasi IoT energy monitoring di 320 titik pengukuran, integrasi dengan dashboard BMS cloud-based, serta otomatisasi pencahayaan dan pendingin berdasarkan occupancy sensor. Optimasi jadwal operasi lift untuk mengurangi peak demand.',
      results: [
        { metric: 'Penurunan Konsumsi Energi', value: '28%' },
        { metric: 'Pengurangan Peak Demand', value: '22%' },
        { metric: 'Payback Period', value: '24 bulan' },
        { metric: 'CO₂ Avoided', value: '840 ton/tahun' },
      ],
      testimonial: {
        quote: 'Dashboard real-time memberikan kami visibilitas yang sebelumnya tidak ada. Kami bisa melihat pemborosan energi per lantai dan mengambil tindakan cepat.',
        author: 'Rina Sari',
        role: 'Facility Director',
      },
    },
    {
      slug: 'panel-surya-kawasan-industri',
      title: 'Panel Surya - Kawasan Industri',
      category: 'Solar Solutions',
      img: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=1200',
      desc: 'Instalasi panel surya atap yang menghasilkan 2,5 MW untuk kompleks manufaktur.',
      client: 'Kompleks Manufaktur Elektronik — Bekasi',
      location: 'Bekasi, Jawa Barat',
      year: '2023',
      duration: '10 bulan',
      problem: 'Kompleks manufaktur seluas 80.000 m² dengan konsumsi listrik 5.200.000 kWh/tahun ingin mengurangi ketergantungan pada PLN dan mencapai target Net Zero 2030.',
      solution: 'Instalasi 5.200 panel surya monokristal 480Wp di atap gedung produksi dan gudang, dengan inverter string 100kW. Sistem hybrid dengan battery storage 2 MWh untuk mengantisipasi grid outage. Monitoring via dashboard solar production real-time.',
      results: [
        { metric: 'Kapasitas Instalasi', value: '2,5 MWp' },
        { metric: 'Energi Tahunan', value: '3.120 MWh' },
        { metric: 'Penghematan Listrik', value: 'Rp 3,7 miliar/tahun' },
        { metric: 'CO₂ Avoided', value: '2.496 ton/tahun' },
      ],
      testimonial: {
        quote: 'Investasi surya yang dikelola BGE memberikan ROI lebih cepat dari proyeksi. Tim mereka sangat profesional dari desain hingga commissioning.',
        author: 'Budi Hartono',
        role: 'VP Operations',
      },
    },
    {
      slug: 'cooling-tower-data-center',
      title: 'Cooling Tower - Data Center',
      category: 'Cooling System',
      img: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&q=80&w=1200',
      desc: 'Implementasi cooling tower efisiensi tinggi untuk menjaga suhu server 24/7.',
      client: 'Penyedia Cloud Services — Jakarta',
      location: 'Jakarta Pusat',
      year: '2024',
      duration: '4 bulan',
      problem: 'Data center Tier 3 dengan PUE 1.9 — terlalu tinggi untuk standar modern. Sistem pendingin air yang ada tidak mampu mengimbangi pertumbuhan beban server 15% per tahun, menyebabkan hotspot di beberapa rack.',
      solution: 'Ganti cooling tower konvensional dengan induced-draft counterflow cooling tower berkapasitas 800 RT. Tambahkan waterside economizer untuk free cooling saat suhu outdoor < 24°C. Implementasi hot aisle containment dan AI-based thermal management.',
      results: [
        { metric: 'PUE Improvement', value: '1.9 → 1.35' },
        { metric: 'Free Cooling Hours', value: '3.200 jam/tahun' },
        { metric: 'Penghematan Energi', value: '42%' },
        { metric: 'Payback Period', value: '20 bulan' },
      ],
    },
    {
      slug: 'boiler-biomassa-tekstil',
      title: 'Boiler Biomassa - Industri Tekstil',
      category: 'Green Energy',
      img: 'https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?auto=format&fit=crop&q=80&w=1200',
      desc: 'Transisi dari bahan bakar fosil ke boiler biomassa untuk mengurangi emisi karbon.',
      client: 'Pabrik Tekstil — Jawa Tengah',
      location: 'Semarang, Jawa Tengah',
      year: '2023',
      duration: '12 bulan',
      problem: 'Pabrik tekstil mengonsumsi 3.000 ton solar/tahun untuk proses pewarnaan dan pengeringan. Biaya bahan bakar naik 25% dalam 3 tahun terakhir, dan tekanan regulasi karbon semakin ketat.',
      solution: 'Instalasi boiler biomassa 20 ton/jam yang menggunakan campuran serbuk gergaji dan tempurung kelapa. Sistem feed water treatment, ash handling, dan stack gas monitoring untuk memenuhi baku mutu emisi. Peralatan dari startup sampai full operation dalam 8 bulan.',
      results: [
        { metric: 'Pengurangan Emisi CO₂', value: '65%' },
        { metric: 'Penghematan Biaya BBM', value: '40%' },
        { metric: 'Kapasitas Uap', value: '20 ton/jam' },
        { metric: 'ROI', value: '24 bulan' },
      ],
      testimonial: {
        quote: 'Transisi ke biomassa membuat kami tidak hanya menghemat biaya, tapi juga memenuhi target sustainability yang dijanjikan ke buyer internasional.',
        author: 'Dewi Anggraini',
        role: 'CSR & Sustainability Manager',
      },
    },
    {
      slug: 'audit-energi-hotel-bintang-5',
      title: 'Audit Energi - Hotel Bintang 5',
      category: 'Energy Audit',
      img: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1200',
      desc: 'Audit energi menyeluruh dan implementasi strategi efisiensi pencahayaan dan pendinginan.',
      client: 'Hotel Bintang 5 — Bali',
      location: 'Kuta, Bali',
      year: '2024',
      duration: '3 bulan',
      problem: 'Hotel 320 kamar dengan konsumsi energi 4.800 MWh/tahun. Energy cost mencapai 12% dari total operating expense — di atas rata-rata industri hospitality 8%.',
      solution: 'Energy audit komprehensif mencakup electrical, mechanical, dan thermal analysis. Implementasi LED lighting (1.200 titik), VRF system untuk guest room, solar water heating (200 kamar), dan occupancy-based HVAC control.',
      results: [
        { metric: 'Total Penghematan', value: '32%' },
        { metric: 'Energy Cost Reduction', value: 'Rp 2,1 miliar/tahun' },
        { metric: 'Carbon Footprint', value: '-480 ton CO₂/tahun' },
        { metric: 'Guest Satisfaction', value: '+15%' },
      ],
      testimonial: {
        quote: 'Audit BGE membuka mata kami tentang betapa banyaknya pemborosan energi yang tidak kami sadari. Hasilnya luar biasa.',
        author: 'Made Wijaya',
        role: 'General Manager',
      },
    },
  ],
  en: [
    {
      slug: 'hvac-optimization-food-factory',
      title: 'HVAC Optimization - Food Factory',
      category: 'HVAC Optimization',
      img: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=1200',
      desc: 'Complete HVAC system redesign for a major food processing facility.',
      client: 'Snack Manufacturing Plant — West Java',
      location: 'Bandung, West Java',
      year: '2024',
      duration: '6 months',
      problem: 'A 15,000 m² food processing facility facing Rp 450 million/month electricity bills for cooling. The 12-year-old HVAC system operated below optimal capacity with an average COP of 2.8 — far below the 5.0+ industry standard.',
      solution: 'Full cooling system audit and redesign using a 500 RT LiBr Absorption Chiller that utilizes waste heat from production boilers. Added Variable Speed Drives (VSD) to 18 fan coil units and a BMS (Building Management System) for real-time monitoring.',
      results: [
        { metric: 'Energy Savings', value: '35%' },
        { metric: 'ROI', value: '18 months' },
        { metric: 'New COP', value: '5.2' },
        { metric: 'Electricity Bill Reduction', value: 'Rp 157M/month' },
      ],
      testimonial: {
        quote: 'BGE transformed our cooling system from the biggest cost center into an efficiency asset. The 35% savings exceeded our expectations.',
        author: 'Andi Kurniawan',
        role: 'Plant Manager',
      },
    },
    {
      slug: 'energy-management-office-building',
      title: 'Energy Management System - Office Building',
      category: 'Energy Management',
      img: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200',
      desc: 'Integrated energy management system for a 20-story corporate headquarters.',
      client: 'Property Corporation — South Jakarta',
      location: 'South Jakarta',
      year: '2024',
      duration: '8 months',
      problem: 'A 20-story, 45,000 m² office building consuming 2,800,000 kWh/year. No centralized monitoring system, making energy waste from lighting, HVAC, and elevators undetectable.',
      solution: 'IoT energy monitoring at 320 measurement points, cloud-based BMS dashboard integration, and automated lighting and cooling based on occupancy sensors. Elevator schedule optimization to reduce peak demand.',
      results: [
        { metric: 'Energy Reduction', value: '28%' },
        { metric: 'Peak Demand Reduction', value: '22%' },
        { metric: 'Payback Period', value: '24 months' },
        { metric: 'CO₂ Avoided', value: '840 tons/year' },
      ],
    },
    {
      slug: 'solar-panels-industrial-park',
      title: 'Solar Panels - Industrial Park',
      category: 'Solar Solutions',
      img: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=1200',
      desc: 'Rooftop solar installation generating 2.5 MW for a manufacturing complex.',
      client: 'Electronics Manufacturing Complex — Bekasi',
      location: 'Bekasi, West Java',
      year: '2023',
      duration: '10 months',
      problem: 'An 80,000 m² manufacturing complex consuming 5,200,000 kWh/year wanted to reduce PLN dependence and achieve Net Zero by 2030.',
      solution: 'Installation of 5,200 monocrystalline 480Wp solar panels on production and warehouse rooftops, with 100kW string inverters. Hybrid system with 2 MWh battery storage for grid outage contingency. Real-time solar production monitoring dashboard.',
      results: [
        { metric: 'Installation Capacity', value: '2.5 MWp' },
        { metric: 'Annual Energy', value: '3,120 MWh' },
        { metric: 'Electricity Savings', value: 'Rp 3.7B/year' },
        { metric: 'CO₂ Avoided', value: '2,496 tons/year' },
      ],
    },
    {
      slug: 'cooling-tower-data-center',
      title: 'Cooling Tower - Data Center',
      category: 'Cooling System',
      img: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&q=80&w=1200',
      desc: 'High-efficiency cooling tower for 24/7 data center server temperature control.',
      client: 'Cloud Services Provider — Jakarta',
      location: 'Central Jakarta',
      year: '2024',
      duration: '4 months',
      problem: 'Tier 3 data center with PUE 1.9 — too high for modern standards. Existing water cooling system unable to keep up with 15% annual server load growth, causing hotspots in several racks.',
      solution: 'Replace conventional cooling tower with induced-draft counterflow cooling tower rated at 800 RT. Add waterside economizer for free cooling when outdoor temperature < 24°C. Implement hot aisle containment and AI-based thermal management.',
      results: [
        { metric: 'PUE Improvement', value: '1.9 → 1.35' },
        { metric: 'Free Cooling Hours', value: '3,200 hours/year' },
        { metric: 'Energy Savings', value: '42%' },
        { metric: 'Payback Period', value: '20 months' },
      ],
    },
    {
      slug: 'biomass-boiler-textile-industry',
      title: 'Biomass Boiler - Textile Industry',
      category: 'Green Energy',
      img: 'https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?auto=format&fit=crop&q=80&w=1200',
      desc: 'Transition from fossil fuels to biomass boilers to reduce carbon emissions.',
      client: 'Textile Manufacturing Plant — Central Java',
      location: 'Semarang, Central Java',
      year: '2023',
      duration: '12 months',
      problem: 'Textile factory consuming 3,000 tons of diesel/year for dyeing and drying processes. Fuel costs rose 25% in 3 years, with increasing carbon regulation pressure.',
      solution: 'Installation of a 20-ton/hour biomass boiler using a mix of sawdust and coconut shell. Feed water treatment, ash handling, and stack gas monitoring systems for emission compliance. From startup to full operation in 8 months.',
      results: [
        { metric: 'CO₂ Emission Reduction', value: '65%' },
        { metric: 'Fuel Cost Savings', value: '40%' },
        { metric: 'Steam Capacity', value: '20 tons/hour' },
        { metric: 'ROI', value: '24 months' },
      ],
    },
    {
      slug: 'energy-audit-5-star-hotel',
      title: 'Energy Audit - 5-Star Hotel',
      category: 'Energy Audit',
      img: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1200',
      desc: 'Comprehensive energy audit and lighting/cooling efficiency strategies.',
      client: '5-Star Hotel — Bali',
      location: 'Kuta, Bali',
      year: '2024',
      duration: '3 months',
      problem: 'A 320-room hotel consuming 4,800 MWh/year. Energy cost reaching 12% of total operating expense — above the 8% hospitality industry average.',
      solution: 'Comprehensive energy audit covering electrical, mechanical, and thermal analysis. LED lighting implementation (1,200 points), VRF system for guest rooms, solar water heating (200 rooms), and occupancy-based HVAC control.',
      results: [
        { metric: 'Total Savings', value: '32%' },
        { metric: 'Energy Cost Reduction', value: 'Rp 2.1B/year' },
        { metric: 'Carbon Footprint', value: '-480 tons CO₂/year' },
        { metric: 'Guest Satisfaction', value: '+15%' },
      ],
    },
  ],
}

export function getProject(lang: string, slug: string): Project | undefined {
  const list = projects[lang === 'en' ? 'en' : 'id']
  return list.find((p) => p.slug === slug)
}
